CREATE TABLE IF NOT EXISTS sagas (
  id UUID PRIMARY KEY,
  type TEXT NOT NULL,
  state TEXT NOT NULL, -- 'STARTED' | 'COMPLETED' | 'FAILED' | 'COMPENSATING'
  payload JSONB NOT NULL,
  steps_completed TEXT[] NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS outbox (
  id BIGSERIAL PRIMARY KEY,
  saga_id UUID NOT NULL,
  event_type TEXT NOT NULL,
  payload JSONB NOT NULL,
  processed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
